### ISSUE TITLE
Would you be interested in ADAU1701 / I2C support?

### ISSUE THREAD

**Issue by m0n5t3r** [elagil/sigmadsp#12]
**Is your feature request related to a problem? Please describe.**
I needed to talk to a Wondom JAB3 amp board, this was the thing second closest to what I needed (the closest was https://github.com/brightcloudy/dsp-python because it's simple, uses I2C and has a good way to configure registers).

**Describe the solution you'd like**
I managed to add support already:
* `I2cHandler` class heavily inspired by dsp-python (I managed to get that one to work first) 
* `Adau1701` class implementing some chip-specific things
* `TCPIP1701` protocol support (turns out it's different and there's no way to tell from the header) - documented at https://ez.analog.com/cfs-file/__key/communityserver-discussions-components-files/396/5432.Sigma-Adau-1x01-TCP_2D00_IP-Documentation.pdf
* safeload support (the ADAU1701 hardware kind) - I've put it in the i2c handler for expediency, but it doesn't belong there, as far as I understand newer chips have some sort of software safeload mechanism, so it's chip specific
* backend code to connect the above

**Describe alternatives you've considered**
Just writing my own starting from dsp-python (where I've already got a comms / parameter updating library working, but without sigmatcp server or params file support); honestly, this one looks a little bit overcomplicated with all of the piping and threads (tracing information flow was ... tedious) and grpcio, which took 14 hours to install on the raspberrypi 1 model B I had available for the task; the frontend is pretty much unusable, it takes 3-4 seconds to send an "adjust volume" call :P

**Additional context**
I'm not much of a Python developer, but I've already tried to follow surrounding coding style, so the things I'd need to do for a PR would be:
* fix gems like `self.spi_handler = I2cHandler()`
* restore the original sigma tcp server, keep my modifications as a new class and select based on configuration / chip type
* move chip operations from the backend to the chip class (the backend shouldn't have a spi handler, it should call the chip-specific class to do its bidding)
* get the style checker thing running and comply with its demands

**Comment by elagil** [comment]
Sure, I would generally add ADAU1701 support, but I cannot test it myself. You may create an initial PR, and I can have a look at it. It doesn't initially have to adhere to all coding style conventions. When the project becomes more complicated, tests should also be added, and I will think of a good way to do this.

> this one looks a little bit overcomplicated with all of the piping and threads
For debugging, using VSCode and an SSH remote connection makes it rather easy. Separating the application into threads gives me flexibility and module separation.

> grpcio
I only tested on an RPi 4, so I cannot comment on the performance issues. I use grpcio, because it makes it possible to use a frontend on a different device, such as a phone, to control your DSP over the network.

**Comment by m0n5t3r** [comment]
same for me with 145x :)

I got it to work again after reshuffling things as stated above, waiting for the first PR to get through before I send the second one

**Comment by m0n5t3r** [comment]
fixed by #13 and #14
